from app.main import app
from fastapi.testclient import TestClient

expected_paths = {
    "/albums/collection/{token}": {"get"},
    "/albums/file/{token}": {"get"},
    "/collections": {"get", "post"},
    "/collections/add-files": {"post"},
    "/collections/file": {"get"},
    "/collections/join-link": {"post"},
    "/collections/leave/{collection_id}": {"post"},
    "/collections/magic-metadata": {"put"},
    "/collections/move-files": {"post"},
    "/collections/public-magic-metadata": {"put"},
    "/collections/rename": {"post"},
    "/collections/restore-files": {"post"},
    "/collections/share": {"post"},
    "/collections/share-url": {"post", "put"},
    "/collections/share-url/{collection_id}": {"delete"},
    "/collections/sharee-magic-metadata": {"put"},
    "/collections/sharees": {"get"},
    "/collections/unshare": {"post"},
    "/collections/v2": {"get"},
    "/collections/v2/diff": {"get"},
    "/collections/v3": {"get"},
    "/collections/v3/remove-files": {"post"},
    "/collections/v3/{collection_id}": {"delete"},
    "/collections/{collection_id}": {"get"},
    "/files": {"post"},
    "/files/copy": {"post"},
    "/files/count": {"get"},
    "/files/download/v2/{file_id}": {"get"},
    "/files/data": {"put"},
    "/files/data/fetch": {"post", "get"},
    "/files/data/preview": {"get"},
    "/files/data/preview-upload-url": {"get"},
    "/files/data/status-diff": {"post"},
    "/files/delete": {"post"},
    "/files/download/{file_id}": {"get"},
    "/files/duplicates": {"get"},
    "/files/info": {"post"},
    "/files/magic-metadata": {"put"},
    "/files/meta": {"post"},
    "/files/public-magic-metadata": {"put"},
    "/files/multipart-complete": {"post"},
    "/files/multipart-upload-url": {"post"},
    "/files/multipart-upload-urls": {"get"},
    "/files/preview/v2/{file_id}": {"get"},
    "/files/preview/{file_id}": {"get"},
    "/files/restore": {"post"},
    "/files/share-url": {"post", "put"},
    "/files/share-url/{file_id}": {"delete"},
    "/files/share-urls": {"get"},
    "/files/share-urls/": {"get"},
    "/files/large-thumbnails": {"get"},
    "/files/size": {"post"},
    "/files/thumbnail": {"put"},
    "/files/trash": {"post"},
    "/files/update": {"put"},
    "/files/upload-url": {"post"},
    "/files/upload-urls": {"get"},
    "/files/video-data": {"put"},
    "/file-link/file": {"get"},
    "/file-link/info": {"get"},
    "/file-link/pass-info": {"get"},
    "/file-link/thumbnail": {"get"},
    "/file-link/verify-password": {"post"},
    "/healthz": {"get"},
    "/kex/add": {"put"},
    "/kex/get": {"get"},
    "/local-storage/{tier}/{object_path}": {"put", "head", "get"},
    "/ping": {"get"},
    "/public-collection/diff": {"get"},
    "/public-collection/file": {"post"},
    "/public-collection/files/data/fetch": {"get"},
    "/public-collection/files/data/preview": {"get"},
    "/public-collection/files/download/{file_id}": {"get"},
    "/public-collection/files/preview/{file_id}": {"get"},
    "/public-collection/info": {"get"},
    "/public-collection/multipart-complete": {"post"},
    "/public-collection/multipart-upload-urls": {"get"},
    "/public-collection/upload-urls": {"get"},
    "/public-collection/verify-password": {"post"},
    "/public/collections": {"post"},
    "/public/collections/{token}": {"get"},
    "/public/collections/{token}/commit-file": {"post"},
    "/public/collections/{token}/preview/{file_id}": {"get"},
    "/public/files/{token}": {"get"},
    "/storage/admin/bonus/{user_id}": {"post"},
    "/storage/admin/quota/{user_id}": {"put"},
    "/storage/admin/usage/{user_id}": {"get"},
    "/storage/detailed-usage": {"get"},
    "/storage/refresh": {"post"},
    "/storage/replication-info": {"get"},
    "/storage/tier-quotas": {"get"},
    "/storage/usage": {"get"},
    "/trash/delete": {"post"},
    "/trash/empty": {"post"},
    "/trash/v2/diff": {"get"},
    "/users/accounts-token": {"get"},
    "/users/login": {"post"},
    "/users/sessions": {"get"},
    "/users/sessions/current": {"delete"},
    "/users/sessions/revoke-others": {"post"},
    "/users/sessions/{session_id}": {"delete"},
    "/version": {"get"},
}

def test_api_paths_match_backend_spec():
    client = TestClient(app)
    openapi = client.get("/openapi.json").json()
    actual_paths = {path: set(info.keys()) for path, info in openapi["paths"].items()}
    assert actual_paths == expected_paths
